_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

# AcmeTaskUiWebBundle routes (to be removed)
acme_task_web:
    resource: "@AcmeTaskUiWebBundle/Resources/config/routing.xml"
    prefix:   /
